name = "SCPLib"
uuid = "372d3413-d610-491c-84c4-e7782b0b6c35"
authors = ["Yuri <yuri.shimane@gmail.com>"]
version = "0.1.0"

[deps]
Clarabel = "61c947e1-3e6d-4ee4-985a-eec8c727bd6e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseDiffTools = "47a9eef4-7e08-11e9-0b38-333d64bd3804"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

